server:
    port: 9005

spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:${http://localhost:9003}/
  datasource:
    password: user_123
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_123
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
