server:
  port: 9005

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${http://localhost:9003}/
management:
  endpoints:
    web:
      expose:
        include: '*'

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_ADDRESS:http://localhost:8761/eureka}



