server:
  port: 9001

#logging:
#  level:
#    root: DEBUG

spring:
  application:
    name: APPUSER-SERVICE
  config:
    import: optional:configserver:${http://localhost:9003}/
  datasource:
    password: user_123
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.mailtrap.io
    password: 70207628a165b6
    port: 2525
    username: a0dbe590d38dce


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${SERVICE-REGISTRY:http://localhost:8761/eureka}


