server:
  port: 9001

#logging:
#  level:
#    root: DEBUG

spring:
  application:
    name: APPUSER-SERVICE
  config:
    import: optional:configserver:${http://localhost:9003}/
  datasource:
    password: user_123
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirectUri: "http://127.0.0.1:9001/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9005
  mail:
    host: smtp.mailtrap.io
    password: 70207628a165b6
    port: 2525
    username: a0dbe590d38dce


token:
  expired:
    at: 360000


client:
  id: auth-service
  secret: auth-secret
  resourceIds: *



