server:
  port: 9003

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Logic-Software-Engineering/karakata-config-server
          clone-on-start: true
        bootstrap: true
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${service-registry:http://localhost:8761/eureka}